SELECT
'RBC~VN~C_PRTY~PRTY~4' AS PROCESS_ID,
'VN' AS C_CNTRY,
'Vietnam' AS NM_CNTRY,
CPI.PRTY_SROGT_ID AS s_prty,
CPI.PRTY_CD AS id_type,
UPPER(CPI.ID_REF) AS N_CUST,
PRTY.PRTY_TYPE_CD AS c_prty_typ,
PRTY.PRTY_TYPE_DESC AS x_prty_typ,
PRTY.PRTY_CLAS AS c_prty_clas,
PRTY.DOM_PRTY_REF AS n_dom_cust,
PRTY.DOM_PRTY_REF_TYPE AS x_prtyref_typ,
PRTY.ENTRP_PRTY_SROGT_ID AS s_entrp_prty,
PRTY.ENTRP_PRTY_REF AS n_entrp_prty,
PRTY.ENTRP_PARNT_PRTY_SROGT_ID AS s_entrp_prnt_prty,
PRTY.ENTRP_PARNT_PRTY_HOST_NUM AS n_entrp_prnt_prty,
PRTY.STS_CD AS c_custsts,
PRTY.STS_DESC AS x_rel_sts,
PRTY.STS_EFF_DT AS d_rel_sts_updt,
PRTY.SEGMT_CD AS c_custseg,
PRTY.SEGMT_DESC AS x_custseg,
PRTY.SUB_SEGMT_CD AS C_CUSTSUBSEG,
PRTY.SUB_SEGMT_CD_DESC AS X_CUSTSUBSEG,
PRTY.DT_OF_BIRTH AS D_BIRTH,
PRTY.GNDR_CD AS C_GNDR,
PRTY.GNDR_DESC AS X_GNDR,
PRTY.PRFNL_CD AS C_PRO,
PRTY.PRFNL_DESC AS X_PRO,
PRTY.MRTL_STS_CD AS C_MARSTS,
PRTY.MRTL_STS_DESC AS X_MARSTS,
PRTY.PAYR_IND AS F_PYR,
PRTY.SCB_STAF_FL AS F_STAFF,
PRTY.EDU_LVL_CD AS C_EDULVL,
PRTY.EDU_LVL_DESC AS X_EDULVL,
PRTY.ANL_INCM_AMT AS A_ANL_INCM,
PRTY.DEPENDANT_CNT AS K_DPNDNT,
PRTY.INCORPORATION_DT AS D_BIZESTBLS,
PRTY.INCORPORATION_CTRY_CD AS C_INCORP_CTRY,
PRTY.ISIC_CD AS C_ISIC,
PRTY.ISIC_DESC AS X_ISIC,
PRTY.DMCLE_CTRY_CD AS C_DMCLE_CNTRY,
PRTY.INTRNL_CR_GRADE AS C_INTRNL_CR_GRD,
PRTY.INTRNL_CR_GRADE_DESC AS X_INTRNL_CR_GRD,
PRTY.IBNK_FAC_FL AS F_IBK,
PRTY.EMP_TP_CD AS C_EMPTYP,
PRTY.EMP_TP_DESC AS X_EMPTYP,
PRTY.GR_MTHLY_INCM_AMT AS A_GR_MTHLY_INCM,
PRTY.RES_STS_CD AS C_RES_STS,
PRTY.RES_STS_DESC AS X_RES_STS,
PRTY.RES_CTRY_CD AS C_RESICNTRY,
PRTY.ARM_CD AS C_ARM,
PRTY.ETHC_CD AS c_ethc,
PRTY.ETHC_DESC AS x_ethc,
PRTY.SRVC_INDI_CD AS C_SRV_INDI,
NTLTY.NTLTY_CTRY_CD AS C_NAT_CNTRY,
PRTY.SALT_CD AS C_SALT,
PRTY.CUST_EMP_DEPT_NM AS nm_emp_dept,
PRTY.PRTY_SEGMT_CLAS AS X_GLPRTY_TYP,
PRTY.PRTY_SEGMT_ID AS ID_GLPRTY_TYP,
PRTY.OTH_MTHLY_INCM_AMT AS A_OTH_MTHLY_INCM,
PRTY.SPO_MTHLY_INCM_AMT AS A_SPO_MTHLY_INCM,
PRTY.ANL_INCM_LAST_UPD_DT AS D_ANL_INCM_LST_UPD,
PRTY.COR_FL AS F_CORP,
PRTY.BKRPT_DT AS D_BKRPT,
PRTY.BKRPT_ID_FL AS F_BKRPT
FROM (SELECT ANL_INCM_AMT, ANL_INCM_LAST_UPD_DT, ARM_CD, BKRPT_DT, BKRPT_ID_FL, COR_FL, CUST_EMP_DEPT_NM, DEPENDANT_CNT, DMCLE_CTRY_CD, DOM_PRTY_REF, DOM_PRTY_REF_TYPE, DT_OF_BIRTH, EDU_LVL_CD, EDU_LVL_DESC, EMP_TP_CD, EMP_TP_DESC, ENTRP_PARNT_PRTY_HOST_NUM, ENTRP_PARNT_PRTY_SROGT_ID, ENTRP_PRTY_REF, ENTRP_PRTY_SROGT_ID, ETHC_CD, ETHC_DESC, GNDR_CD, GNDR_DESC, GR_MTHLY_INCM_AMT, IBNK_FAC_FL, INCORPORATION_CTRY_CD, INCORPORATION_DT, INTRNL_CR_GRADE, INTRNL_CR_GRADE_DESC, ISIC_CD, ISIC_DESC, MRTL_STS_CD, MRTL_STS_DESC, OTH_MTHLY_INCM_AMT, PAYR_IND, PRFNL_CD, PRFNL_DESC, PRTY_CLAS, PRTY_SEGMT_CLAS, PRTY_SEGMT_ID, PRTY_SROGT_ID, PRTY_TYPE_CD, PRTY_TYPE_DESC, RES_CTRY_CD, RES_STS_CD, RES_STS_DESC, SALT_CD, SCB_STAF_FL, SEGMT_CD, SEGMT_DESC, SPO_MTHLY_INCM_AMT, SRVC_INDI_CD, STS_CD, STS_DESC, STS_EFF_DT, SUB_SEGMT_CD, SUB_SEGMT_CD_DESC FROM C_PRTY
    WHERE DATA_SRC = 'EBB'
   AND SOURCE_COUNTRY_CODE = 'VN'
) PRTY

LEFT JOIN (
    SELECT PRTY_SROGT_ID, ID_REF, PRTY_CD
    FROM C_PRTY_ID
    WHERE DATA_SRC = 'EBB'
   AND SOURCE_COUNTRY_CODE = 'VN'
   AND ID_TP_CD = 'N01'
) CPI
    ON PRTY.PRTY_SROGT_ID = CPI.PRTY_SROGT_ID

LEFT JOIN (SELECT NTLTY_CTRY_CD, PRTY_SROGT_ID FROM C_PRTY_NTLTY
    WHERE DATA_SRC = 'EBB'
   AND SOURCE_COUNTRY_CODE = 'VN'
   AND NTLTY_TYPE_CD = 'CN01'
) NTLTY
    ON PRTY.PRTY_SROGT_ID = NTLTY.PRTY_SROGT_ID;